import {
    GoogleGenerativeAI,
    HarmCategory,
    HarmBlockThreshold,
} from "@google/generative-ai";

const MODEL = "gemini-2.5-flash";
const MAX_DIFF_CHARS = 12000;

export class PRReviewError extends Error {
    constructor(message: string, public readonly cause?: unknown) {
        super(message);
        this.name = "PRReviewError";
    }
}

export interface AIReviewResult {
    summary: string;
    comments: Array<{
        path: string;
        line: number;
        body: string;
    }>;
}

export async function generatePRReview(
    diff: string,
    prTitle: string
): Promise<AIReviewResult> {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new PRReviewError("GEMINI_API_KEY is not set");

    let truncationNote = "";
    let processedDiff = diff;

    if (diff.length > MAX_DIFF_CHARS) {
        processedDiff = diff.slice(0, MAX_DIFF_CHARS);
        truncationNote =
            "\n\n> **Note:** This diff was truncated to 12,000 characters. Some files may not be reviewed.";
    }

    console.log("=== DIFF SENT TO GEMINI ===");
    console.log(processedDiff);
    console.log("===========================");

    const userPrompt = `Review this PR titled: "${prTitle}"

Diff:
${processedDiff}

Rules:
- You are a professional code reviewer. Your review should read like it was written by a real person, not generated by AI.
- Use bullet points, not paragraphs.
- Keep the summary to 3-5 bullet points max.
- Do NOT use emojis. Keep the tone professional and straightforward.
- If the code looks good and nothing is broken:
  - Acknowledge what the PR does in one line.
  - Mention that the changes look good and will be merged shortly.
  - Do NOT over-praise or exaggerate. Just be professional.
- If something is wrong or could break:
  - State the file name and what exactly could go wrong.
  - Explain it simply so a beginner can understand.
  - Suggest a fix if possible.
- Only flag real bugs or things that could break. Skip minor style preferences.
- For inline comments, keep them short and helpful. Explain the problem and suggest a fix.
- You MUST return a valid JSON object matching this schema:
  {
    "summary": "Professional summary in bullet points.",
    "comments": [
      {
        "path": "path/to/file.ts",
        "line": 10,
        "body": "This could cause an issue because X. Consider doing Y instead."
      }
    ]
  }
- If there are no issues, return an empty comments array: "comments": []
- Ensure that the \`path\` matches a file in the diff exactly.
- Ensure that the \`line\` is an exact line number present in the added/modified parts of the diff for that file.
`;

    try {
        const genAI = new GoogleGenerativeAI(apiKey);

        const model = genAI.getGenerativeModel({
            model: MODEL,
            systemInstruction:
                "You are a professional code reviewer at a software company. Write reviews that sound like a real senior developer — concise, professional, and human. Never use emojis. Use bullet points. Be direct but respectful. Always return a raw JSON object.",
            generationConfig: {
                responseMimeType: "application/json",
            },
            safetySettings: [
                {
                    category: HarmCategory.HARM_CATEGORY_HARASSMENT,
                    threshold: HarmBlockThreshold.BLOCK_NONE,
                },
                {
                    category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                    threshold: HarmBlockThreshold.BLOCK_NONE,
                },
            ],
        });

        const result = await model.generateContent(userPrompt);
        const text = result.response.text();

        if (!text) throw new PRReviewError("Gemini returned an empty response");

        const parsed = JSON.parse(text) as AIReviewResult;
        if (truncationNote) {
            parsed.summary += truncationNote;
        }
        return parsed;
    } catch (err) {
        if (err instanceof PRReviewError) throw err;
        throw new PRReviewError("Gemini API call failed", err);
    }
}
